version: '3.9'

services:
  kitchen_order_api:
    container_name: kitchen_order
    image: kitchen_order_image
    build:
      context: ./
    depends_on:
      - kitchen_order_db
      - kitchen_order_redis
    ports:
      - '4004:4004'
    networks:
      - webnet
    volumes:
      - ./:/app
  kitchen_order_db:
    container_name: kitchen_order_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet
  kitchen_order_redis:
    container_name: kitchen_order_redis
    image: redis
    ports:
      - '6379:6379'
    networks:
      - webnet
  pgadmin:
    container_name: kitchen_order_pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - webnet
    logging:
      driver: none
volumes:
  pgdata: {}
  pgadmin-data: {}
networks:
  webnet:
